- name: Installing Nginx on Ubuntu
  hosts: all
  become: yes
      
  tasks:
    - name: Create gjpb-rubi-web-react-ts directory
      file:
        path: /var/www/gjpb/rubi  # Change this path to your desired directory
        state: directory
        mode: '0755'

    - name: Upload build to /var/www/gjpb/rubi
      copy:
        src: "../../../dist/"
        dest: "/var/www/gjpb/rubi"
        mode: 0755
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted